version: '3.8'

services:
  app:
    build: .
    volumes:
      -.:/app
      -.:data:/app/data
    environment:
      - DISPLAY=$DISPLAY
    network_mode: "host"
    devices:
    - /dev/dri:/dev/dri
      -/tmp/.X11-unix:/tmp/.X11-unix
